spring:
  datasource:
    url: ${DEV_MYSQL_URL:jdbc:mysql://127.0.0.1:3306/ai_investor?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true}
    username: ${DEV_MYSQL_USERNAME:}
    password: ${DEV_MYSQL_PASSWORD:}
  data:
    redis:
      host: ${DEV_REDIS_HOST:127.0.0.1}
      port: ${DEV_REDIS_PORT:6379}
      password: ${DEV_REDIS_PASSWORD:}
  rabbitmq:
    host: ${DEV_RABBITMQ_HOST:127.0.0.1}
    port: ${DEV_RABBITMQ_PORT:5672}
    username: ${DEV_RABBITMQ_USERNAME:}
    password: ${DEV_RABBITMQ_PASSWORD:}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
