DROP TABLE IF EXISTS ai_ingest_registry;
--;;
DROP TABLE IF EXISTS user_profiles;
--;;
DROP INDEX IF EXISTS idx_ai_chat_turns_user_session_created;
--;;
DROP INDEX IF EXISTS idx_ai_chat_turns_user_created;
--;;
DROP TABLE IF EXISTS ai_chat_turns;
--;;
DROP INDEX IF EXISTS idx_ai_agent_runs_created_at;
--;;
DROP INDEX IF EXISTS idx_ai_agent_runs_thread_id;
--;;
DROP INDEX IF EXISTS idx_ai_agent_runs_trace_id;
--;;
DROP TABLE IF EXISTS ai_agent_runs;
--;;
DROP INDEX IF EXISTS idx_doc_chunks_source;
--;;
DROP INDEX IF EXISTS idx_doc_chunks_embedding;
--;;
DROP TABLE IF EXISTS doc_chunks;
